### ISSUE TITLE
Break up the code with functions

### ISSUE THREAD

**Issue by HenrySoftwareStudio** [import-brain/caesar#1]
code is too long and too hard to read.
according to your idea, your project can be break up to
1. input
2. pre-encryption processing
3. encryption
4. post-encryption processing
5. output

each can be its own function and pass values between each other with a pointer (I have no idea how but it should work out).

**Comment by import-brain** [comment]
Because this is for CS50, I think I just have to start over and write it using functions like you said.

Reading this spaghetti code is hurting my brain

**Comment by HenrySoftwareStudio** [comment]
I tried C, too complicated. I will make a C# one, though.

**Comment by import-brain** [comment]
Thank you so much for telling me to use a function, I finally fixed the segmentation faults! Will credit you in CONTRIBUTORS
